/*!
  * mapfre : Angular Parent Mapfre
  * @version v5.4.0
  * @author Marcos Peralta <marcos.peralta@konecta.com.py>
  * @date 2019-08-06
  */

;
//asignar un nombre y versión al cache
const CACHE_NAME = 'v1_cache_mapfre',
  urlsToCache = [
    /* CSS */
    './css/main.css',
    './css/main.css.map',
    './css/angular-material/angular-material.css',
    './css/angular-material/angular-material.min.css',
    './css/angular-material/layouts/angular-material.layout-attributes.css',
    './css/angular-material/layouts/angular-material.layout-attributes.min.css',
    './css/angular-material/layouts/angular-material.layouts.css',
    './css/angular-material/layouts/angular-material.layouts.ie_fixes.css',
    './css/angular-material/layouts/angular-material.layouts.min.css',
    './css/angular-material/modules/closure/autocomplete/autocomplete-default-theme.css',
    './css/angular-material/modules/closure/autocomplete/autocomplete-default-theme.min.css',
    './css/angular-material/modules/closure/autocomplete/autocomplete.css',
    './css/angular-material/modules/closure/autocomplete/autocomplete.min.css',
    './css/angular-material/modules/closure/backdrop/backdrop-default-theme.css',
    './css/angular-material/modules/closure/backdrop/backdrop-default-theme.min.css',
    './css/angular-material/modules/closure/backdrop/backdrop.css',
    './css/angular-material/modules/closure/backdrop/backdrop.min.css',
    './css/angular-material/modules/closure/bottomSheet/bottomSheet-default-theme.css',
    './css/angular-material/modules/closure/bottomSheet/bottomSheet-default-theme.min.css',
    './css/angular-material/modules/closure/bottomSheet/bottomSheet.css',
    './css/angular-material/modules/closure/bottomSheet/bottomSheet.min.css',
    './css/angular-material/modules/closure/button/button-default-theme.css',
    './css/angular-material/modules/closure/button/button-default-theme.min.css',
    './css/angular-material/modules/closure/button/button.css',
    './css/angular-material/modules/closure/button/button.min.css',
    './css/angular-material/modules/closure/card/card-default-theme.css',
    './css/angular-material/modules/closure/card/card-default-theme.min.css',
    './css/angular-material/modules/closure/card/card.css',
    './css/angular-material/modules/closure/card/card.min.css',
    './css/angular-material/modules/closure/checkbox/checkbox-default-theme.css',
    './css/angular-material/modules/closure/checkbox/checkbox-default-theme.min.css',
    './css/angular-material/modules/closure/checkbox/checkbox.css',
    './css/angular-material/modules/closure/checkbox/checkbox.min.css',
    './css/angular-material/modules/closure/chips/chips-default-theme.css',
    './css/angular-material/modules/closure/chips/chips-default-theme.min.css',
    './css/angular-material/modules/closure/chips/chips.css',
    './css/angular-material/modules/closure/chips/chips.min.css',
    './css/angular-material/modules/closure/content/content-default-theme.css',
    './css/angular-material/modules/closure/content/content-default-theme.min.css',
    './css/angular-material/modules/closure/content/content.css',
    './css/angular-material/modules/closure/content/content.min.css',
    './css/angular-material/modules/closure/core/core-default-theme.css',
    './css/angular-material/modules/closure/core/core-default-theme.min.css',
    './css/angular-material/modules/closure/core/core.css',
    './css/angular-material/modules/closure/core/core.min.css',
    './css/angular-material/modules/closure/datepicker/datepicker-default-theme.css',
    './css/angular-material/modules/closure/datepicker/datepicker-default-theme.min.css',
    './css/angular-material/modules/closure/datepicker/datepicker.css',
    './css/angular-material/modules/closure/datepicker/datepicker.min.css',
    './css/angular-material/modules/closure/dialog/dialog-default-theme.css',
    './css/angular-material/modules/closure/dialog/dialog-default-theme.min.css',
    './css/angular-material/modules/closure/dialog/dialog.css',
    './css/angular-material/modules/closure/dialog/dialog.min.css',
    './css/angular-material/modules/closure/divider/divider-default-theme.css',
    './css/angular-material/modules/closure/divider/divider-default-theme.min.css',
    './css/angular-material/modules/closure/divider/divider.css',
    './css/angular-material/modules/closure/divider/divider.min.css',
    './css/angular-material/modules/closure/fabSpeedDial/fabSpeedDial.css',
    './css/angular-material/modules/closure/fabSpeedDial/fabSpeedDial.min.css',
    './css/angular-material/modules/closure/fabToolbar/fabToolbar.css',
    './css/angular-material/modules/closure/fabToolbar/fabToolbar.min.css',
    './css/angular-material/modules/closure/gridList/gridList-default-theme.css',
    './css/angular-material/modules/closure/gridList/gridList.css',
    './css/angular-material/modules/closure/gridList/gridList.min.css',
    './css/angular-material/modules/closure/icon/icon-default-theme.css',
    './css/angular-material/modules/closure/icon/icon-default-theme.min.css',
    './css/angular-material/modules/closure/icon/icon.css',
    './css/angular-material/modules/closure/icon/icon.min.css',
    './css/angular-material/modules/closure/input/input-default-theme.css',
    './css/angular-material/modules/closure/input/input-default-theme.min.css',
    './css/angular-material/modules/closure/input/input.css',
    './css/angular-material/modules/closure/input/input.min.css',
    './css/angular-material/modules/closure/list/list-default-theme.css',
    './css/angular-material/modules/closure/list/list-default-theme.min.css',
    './css/angular-material/modules/closure/list/list.css',
    './css/angular-material/modules/closure/list/list.min.css',
    './css/angular-material/modules/closure/menu/menu-default-theme.css',
    './css/angular-material/modules/closure/menu/menu-default-theme.min.css',
    './css/angular-material/modules/closure/menu/menu.css',
    './css/angular-material/modules/closure/menu/menu.min.css',
    './css/angular-material/modules/closure/menuBar/menuBar-default-theme.css',
    './css/angular-material/modules/closure/menuBar/menuBar-default-theme.min.css',
    './css/angular-material/modules/closure/menuBar/menuBar.css',
    './css/angular-material/modules/closure/menuBar/menuBar.min.css',
    './css/angular-material/modules/closure/navBar/navBar-default-theme.css',
    './css/angular-material/modules/closure/navBar/navBar-default-theme.min.css',
    './css/angular-material/modules/closure/navBar/navBar.css',
    './css/angular-material/modules/closure/navBar/navBar.min.css',
    './css/angular-material/modules/closure/panel/panel-default-theme.css',
    './css/angular-material/modules/closure/panel/panel-default-theme.min.css',
    './css/angular-material/modules/closure/panel/panel.css',
    './css/angular-material/modules/closure/panel/panel.min.css',
    './css/angular-material/modules/closure/progressCircular/progressCircular-default-theme.css',
    './css/angular-material/modules/closure/progressCircular/progressCircular-default-theme.min.css',
    './css/angular-material/modules/closure/progressCircular/progressCircular.css',
    './css/angular-material/modules/closure/progressCircular/progressCircular.min.css',
    './css/angular-material/modules/closure/progressLinear/progressLinear-default-theme.css',
    './css/angular-material/modules/closure/progressLinear/progressLinear-default-theme.min.css',
    './css/angular-material/modules/closure/progressLinear/progressLinear.css',
    './css/angular-material/modules/closure/progressLinear/progressLinear.min.css',
    './css/angular-material/modules/closure/radioButton/radioButton-default-theme.css',
    './css/angular-material/modules/closure/radioButton/radioButton-default-theme.min.css',
    './css/angular-material/modules/closure/radioButton/radioButton.css',
    './css/angular-material/modules/closure/radioButton/radioButton.min.css',
    './css/angular-material/modules/closure/select/select-default-theme.css',
    './css/angular-material/modules/closure/select/select-default-theme.min.css',
    './css/angular-material/modules/closure/select/select.css',
    './css/angular-material/modules/closure/select/select.min.css',
    './css/angular-material/modules/closure/sidenav/sidenav-default-theme.css',
    './css/angular-material/modules/closure/sidenav/sidenav-default-theme.min.css',
    './css/angular-material/modules/closure/sidenav/sidenav.css',
    './css/angular-material/modules/closure/sidenav/sidenav.min.css',
    './css/angular-material/modules/closure/slider/slider-default-theme.css',
    './css/angular-material/modules/closure/slider/slider-default-theme.min.css',
    './css/angular-material/modules/closure/slider/slider.css',
    './css/angular-material/modules/closure/slider/slider.min.css',
    './css/angular-material/modules/closure/sticky/sticky.css',
    './css/angular-material/modules/closure/sticky/sticky.min.css',
    './css/angular-material/modules/closure/subheader/subheader-default-theme.css',
    './css/angular-material/modules/closure/subheader/subheader-default-theme.min.css',
    './css/angular-material/modules/closure/subheader/subheader.css',
    './css/angular-material/modules/closure/subheader/subheader.min.css',
    './css/angular-material/modules/closure/swipe/swipe.css',
    './css/angular-material/modules/closure/swipe/swipe.min.css',
    './css/angular-material/modules/closure/switch/switch-default-theme.css',
    './css/angular-material/modules/closure/switch/switch-default-theme.min.css',
    './css/angular-material/modules/closure/switch/switch.css',
    './css/angular-material/modules/closure/switch/switch.min.css',
    './css/angular-material/modules/closure/tabs/tabs-default-theme.css',
    './css/angular-material/modules/closure/tabs/tabs-default-theme.min.css',
    './css/angular-material/modules/closure/tabs/tabs.css',
    './css/angular-material/modules/closure/tabs/tabs.min.css',
    './css/angular-material/modules/closure/textField/textField-default-theme.css',
    './css/angular-material/modules/closure/textField/textField.css',
    './css/angular-material/modules/closure/toast/toast-default-theme.css',
    './css/angular-material/modules/closure/toast/toast-default-theme.min.css',
    './css/angular-material/modules/closure/toast/toast.css',
    './css/angular-material/modules/closure/toast/toast.min.css',
    './css/angular-material/modules/closure/toolbar/toolbar-default-theme.css',
    './css/angular-material/modules/closure/toolbar/toolbar-default-theme.min.css',
    './css/angular-material/modules/closure/toolbar/toolbar.css',
    './css/angular-material/modules/closure/toolbar/toolbar.min.css',
    './css/angular-material/modules/closure/tooltip/tooltip-default-theme.css',
    './css/angular-material/modules/closure/tooltip/tooltip-default-theme.min.css',
    './css/angular-material/modules/closure/tooltip/tooltip.css',
    './css/angular-material/modules/closure/tooltip/tooltip.min.css',
    './css/angular-material/modules/closure/truncate/truncate.css',
    './css/angular-material/modules/closure/truncate/truncate.min.css',
    './css/angular-material/modules/closure/virtualRepeat/virtualRepeat.css',
    './css/angular-material/modules/closure/virtualRepeat/virtualRepeat.min.css',
    './css/angular-material/modules/closure/whiteframe/whiteframe.css',
    './css/angular-material/modules/closure/whiteframe/whiteframe.min.css',
    './css/angular-material/modules/js/autocomplete/autocomplete-default-theme.css',
    './css/angular-material/modules/js/autocomplete/autocomplete-default-theme.min.css',
    './css/angular-material/modules/js/autocomplete/autocomplete.css',
    './css/angular-material/modules/js/autocomplete/autocomplete.min.css',
    './css/angular-material/modules/js/backdrop/backdrop-default-theme.css',
    './css/angular-material/modules/js/backdrop/backdrop-default-theme.min.css',
    './css/angular-material/modules/js/backdrop/backdrop.css',
    './css/angular-material/modules/js/backdrop/backdrop.min.css',
    './css/angular-material/modules/js/bottomSheet/bottomSheet-default-theme.css',
    './css/angular-material/modules/js/bottomSheet/bottomSheet-default-theme.min.css',
    './css/angular-material/modules/js/bottomSheet/bottomSheet.css',
    './css/angular-material/modules/js/bottomSheet/bottomSheet.min.css',
    './css/angular-material/modules/js/button/button-default-theme.css',
    './css/angular-material/modules/js/button/button-default-theme.min.css',
    './css/angular-material/modules/js/button/button.css',
    './css/angular-material/modules/js/button/button.min.css',
    './css/angular-material/modules/js/card/card-default-theme.css',
    './css/angular-material/modules/js/card/card-default-theme.min.css',
    './css/angular-material/modules/js/card/card.css',
    './css/angular-material/modules/js/card/card.min.css',
    './css/angular-material/modules/js/checkbox/checkbox-default-theme.css',
    './css/angular-material/modules/js/checkbox/checkbox-default-theme.min.css',
    './css/angular-material/modules/js/checkbox/checkbox.css',
    './css/angular-material/modules/js/checkbox/checkbox.min.css',
    './css/angular-material/modules/js/chips/chips-default-theme.css',
    './css/angular-material/modules/js/chips/chips-default-theme.min.css',
    './css/angular-material/modules/js/chips/chips.css',
    './css/angular-material/modules/js/chips/chips.min.css',
    './css/angular-material/modules/js/content/content-default-theme.css',
    './css/angular-material/modules/js/content/content-default-theme.min.css',
    './css/angular-material/modules/js/content/content.css',
    './css/angular-material/modules/js/content/content.min.css',
    './css/angular-material/modules/js/core/core-default-theme.css',
    './css/angular-material/modules/js/core/core-default-theme.min.css',
    './css/angular-material/modules/js/core/core.css',
    './css/angular-material/modules/js/core/core.min.css',
    './css/angular-material/modules/js/datepicker/datepicker-default-theme.css',
    './css/angular-material/modules/js/datepicker/datepicker-default-theme.min.css',
    './css/angular-material/modules/js/datepicker/datepicker.css',
    './css/angular-material/modules/js/datepicker/datepicker.min.css',
    './css/angular-material/modules/js/dialog/dialog-default-theme.css',
    './css/angular-material/modules/js/dialog/dialog-default-theme.min.css',
    './css/angular-material/modules/js/dialog/dialog.css',
    './css/angular-material/modules/js/dialog/dialog.min.css',
    './css/angular-material/modules/js/divider/divider-default-theme.css',
    './css/angular-material/modules/js/divider/divider-default-theme.min.css',
    './css/angular-material/modules/js/divider/divider.css',
    './css/angular-material/modules/js/divider/divider.min.css',
    './css/angular-material/modules/js/fabSpeedDial/fabSpeedDial.css',
    './css/angular-material/modules/js/fabSpeedDial/fabSpeedDial.min.css',
    './css/angular-material/modules/js/fabToolbar/fabToolbar.css',
    './css/angular-material/modules/js/fabToolbar/fabToolbar.min.css',
    './css/angular-material/modules/js/gridList/gridList.css',
    './css/angular-material/modules/js/gridList/gridList.min.css',
    './css/angular-material/modules/js/icon/icon-default-theme.css',
    './css/angular-material/modules/js/icon/icon-default-theme.min.css',
    './css/angular-material/modules/js/icon/icon.css',
    './css/angular-material/modules/js/icon/icon.min.css',
    './css/angular-material/modules/js/input/input-default-theme.css',
    './css/angular-material/modules/js/input/input-default-theme.min.css',
    './css/angular-material/modules/js/input/input.css',
    './css/angular-material/modules/js/input/input.min.css',
    './css/angular-material/modules/js/list/list-default-theme.css',
    './css/angular-material/modules/js/list/list-default-theme.min.css',
    './css/angular-material/modules/js/list/list.css',
    './css/angular-material/modules/js/list/list.min.css',
    './css/angular-material/modules/js/menu/menu-default-theme.css',
    './css/angular-material/modules/js/menu/menu-default-theme.min.css',
    './css/angular-material/modules/js/menu/menu.css',
    './css/angular-material/modules/js/menu/menu.min.css',
    './css/angular-material/modules/js/menuBar/menuBar-default-theme.css',
    './css/angular-material/modules/js/menuBar/menuBar-default-theme.min.css',
    './css/angular-material/modules/js/menuBar/menuBar.css',
    './css/angular-material/modules/js/menuBar/menuBar.min.css',
    './css/angular-material/modules/js/navBar/navBar-default-theme.css',
    './css/angular-material/modules/js/navBar/navBar-default-theme.min.css',
    './css/angular-material/modules/js/navBar/navBar.css',
    './css/angular-material/modules/js/navBar/navBar.min.css',
    './css/angular-material/modules/js/panel/panel-default-theme.css',
    './css/angular-material/modules/js/panel/panel-default-theme.min.css',
    './css/angular-material/modules/js/panel/panel.css',
    './css/angular-material/modules/js/panel/panel.min.css',
    './css/angular-material/modules/js/progressCircular/progressCircular-default-theme.css',
    './css/angular-material/modules/js/progressCircular/progressCircular-default-theme.min.css',
    './css/angular-material/modules/js/progressCircular/progressCircular.css',
    './css/angular-material/modules/js/progressCircular/progressCircular.min.css',
    './css/angular-material/modules/js/progressLinear/progressLinear-default-theme.css',
    './css/angular-material/modules/js/progressLinear/progressLinear-default-theme.min.css',
    './css/angular-material/modules/js/progressLinear/progressLinear.css',
    './css/angular-material/modules/js/progressLinear/progressLinear.min.css',
    './css/angular-material/modules/js/radioButton/radioButton-default-theme.css',
    './css/angular-material/modules/js/radioButton/radioButton-default-theme.min.css',
    './css/angular-material/modules/js/radioButton/radioButton.css',
    './css/angular-material/modules/js/radioButton/radioButton.min.css',
    './css/angular-material/modules/js/select/select-default-theme.css',
    './css/angular-material/modules/js/select/select-default-theme.min.css',
    './css/angular-material/modules/js/select/select.css',
    './css/angular-material/modules/js/select/select.min.css',
    './css/angular-material/modules/js/sidenav/sidenav-default-theme.css',
    './css/angular-material/modules/js/sidenav/sidenav-default-theme.min.css',
    './css/angular-material/modules/js/sidenav/sidenav.css',
    './css/angular-material/modules/js/sidenav/sidenav.min.css',
    './css/angular-material/modules/js/slider/slider-default-theme.css',
    './css/angular-material/modules/js/slider/slider-default-theme.min.css',
    './css/angular-material/modules/js/slider/slider.css',
    './css/angular-material/modules/js/slider/slider.min.css',
    './css/angular-material/modules/js/sticky/sticky.css',
    './css/angular-material/modules/js/sticky/sticky.min.css',
    './css/angular-material/modules/js/subheader/subheader-default-theme.css',
    './css/angular-material/modules/js/subheader/subheader-default-theme.min.css',
    './css/angular-material/modules/js/subheader/subheader.css',
    './css/angular-material/modules/js/subheader/subheader.min.css',
    './css/angular-material/modules/js/swipe/swipe.css',
    './css/angular-material/modules/js/swipe/swipe.min.css',
    './css/angular-material/modules/js/switch/switch-default-theme.css',
    './css/angular-material/modules/js/switch/switch-default-theme.min.css',
    './css/angular-material/modules/js/switch/switch.css',
    './css/angular-material/modules/js/switch/switch.min.css',
    './css/angular-material/modules/js/tabs/tabs-default-theme.css',
    './css/angular-material/modules/js/tabs/tabs-default-theme.min.css',
    './css/angular-material/modules/js/tabs/tabs.css',
    './css/angular-material/modules/js/tabs/tabs.min.css',
    './css/angular-material/modules/js/textField/textField-default-theme.css',
    './css/angular-material/modules/js/textField/textField-default-theme.min.css',
    './css/angular-material/modules/js/textField/textField.css',
    './css/angular-material/modules/js/textField/textField.min.css',
    './css/angular-material/modules/js/toast/toast-default-theme.css',
    './css/angular-material/modules/js/toast/toast-default-theme.min.css',
    './css/angular-material/modules/js/toast/toast.css',
    './css/angular-material/modules/js/toast/toast.min.css',
    './css/angular-material/modules/js/toolbar/toolbar-default-theme.css',
    './css/angular-material/modules/js/toolbar/toolbar-default-theme.min.css',
    './css/angular-material/modules/js/toolbar/toolbar.css',
    './css/angular-material/modules/js/toolbar/toolbar.min.css',
    './css/angular-material/modules/js/tooltip/tooltip-default-theme.css',
    './css/angular-material/modules/js/tooltip/tooltip-default-theme.min.css',
    './css/angular-material/modules/js/tooltip/tooltip.css',
    './css/angular-material/modules/js/tooltip/tooltip.min.css',
    './css/angular-material/modules/js/truncate/truncate.css',
    './css/angular-material/modules/js/truncate/truncate.min.css',
    './css/angular-material/modules/js/virtualRepeat/virtualRepeat.css',
    './css/angular-material/modules/js/virtualRepeat/virtualRepeat.min.css',
    './css/angular-material/modules/js/whiteframe/whiteframe.css',
    './css/angular-material/modules/js/whiteframe/whiteframe.min.css',
    './css/angular-material/modules/layouts/angular-material.layout-attributes.css',
    './css/angular-material/modules/layouts/angular-material.layout-attributes.min.css',
    './css/angular-material/modules/layouts/angular-material.layouts.css',
    './css/angular-material/modules/layouts/angular-material.layouts.ie_fixes.css',
    './css/angular-material/modules/layouts/angular-material.layouts.min.css',
    './css/angular-responsive-tables/angular-responsive-tables.css',
    './css/angular-responsive-tables/angular-responsive-tables.min.css',
    './css/md-time-picker/md-time-picker.css',
    './css/ui-boostrap/ui-bootstrap-csp.css',
    /* END CSS */


    /* FONTS */
    './fonts/fontawesome-webfont.eot',
    './fonts/fontawesome-webfont.svg',
    './fonts/fontawesome-webfont.ttf',
    './fonts/fontawesome-webfont.woff',
    './fonts/fontawesome-webfont.woff2',
    './fonts/FontAwesome.otf',
    './fonts/bootstrap/glyphicons-halflings-regular.eot',
    './fonts/bootstrap/glyphicons-halflings-regular.svg',
    './fonts/bootstrap/glyphicons-halflings-regular.ttf',
    './fonts/bootstrap/glyphicons-halflings-regular.woff',
    './fonts/bootstrap/glyphicons-halflings-regular.woff2',
    /* END FONTS */


    /*SYSTEM IMAGES */
    './images/accesod.png',
    './images/add.png',
    './images/cabecera.png',
    './images/calculator.png',
    './images/cancel_icon.png',
    './images/car.png',
    './images/cargando.gif',
    './images/cerrar.png',
    './images/export.png',
    './images/favicon.ico',
    './images/flechita.png',
    './images/flechita_gris.png',
    './images/flota.png',
    './images/flota1.png',
    './images/fondo.jpg',
    './images/guardar.png',
    './images/icon-llave.png',
    './images/icon1.png',
    './images/icon10.png',
    './images/icon11.png',
    './images/icon11grey.png',
    './images/icon12.png',
    './images/icon12grey.png',
    './images/icon1grey.png',
    './images/icon2.png',
    './images/icon3.png',
    './images/icon3grey.png',
    './images/icon4.png',
    './images/icon4grey.png',
    './images/icon5.png',
    './images/icon5grey.png',
    './images/icon6.png',
    './images/icon6grey.png',
    './images/icon7.png',
    './images/icon7grey.png',
    './images/icon8.png',
    './images/icon9.png',
    './images/iconadjunto.png',
    './images/iconprint_grey.png',
    './images/import.png',
    './images/loader - copia.gif',
    './images/loader.gif',
    './images/lupa.png',
    './images/multiriesgos.png',
    './images/nuevo.png',
    './images/pdf.png',
    './images/pdf_logo.png',
    './images/personas.png',
    './images/porcen.1.png',
    './images/porcen.2.png',
    './images/porcen.png',
    './images/salir - copia.png',
    './images/salir.png',
    './images/salir1.png',
    './images/salir2.png',
    './images/trespuntos.png',
    './images/vehiculo.png',
    './images/ventas-logo-transparent - copia.png',
    './images/ventas-logo-transparent.png',
    './images/ventas-web-logo-ico.png',
    './images/xlsx_logo.png',
    /* END SYSTEM IMAGES */

    /*  CONTROLLERS */
    './libs/app.min.js',
    /*  END CONTROLLERS*/


    './index.html',
    /*  PARTIALS*/
    './partials/dashboard-partial.html',
    './partials/pagina403.html',
    './partials/public-partial.html',
    './partials/common/footer-partial.html',
    './partials/common/header-partial.html',
    './partials/common/sidebar-partial.html',
    './partials/cotizacion-hogar/desktop/cotizacion-hogar-form.html',
    './partials/cotizacion-hogar/mobile/cotizacion-hogar-form.html',
    './partials/cotizacion-hogar-propuesta/desktop/propuesta-hogar-form.html',
    './partials/cotizacion-multi-riesgos/desktop/cotizacion-multiriesgo-form.html',
    './partials/cotizacion-multi-riesgos/mobile/cotizacion-multiriesgo-form.html',
    './partials/cotizacion-vehiculo/desktop/cotizacion-vehiculo-form.html',
    './partials/cotizacion-vehiculo/mobile/cotizacion-vehiculo-form.html',
    './partials/cotizacion-vehiculo - copia/desktop/cotizacion-vehiculo-form.html',
    './partials/dual-list/dual-concesionarias.html',
    './partials/dual-list/dual-marcas.html',
    './partials/flota/desktop/flota-agregar.html',
    './partials/flota/desktop/flota-form.html',
    './partials/login/login.html',
    './partials/preferencia/preferencia-list.html',
    './partials/propuesta-flota/desktop/asegurado-flota-form.html',
    './partials/propuesta-flota/desktop/documentos-form.html',
    './partials/propuesta-flota/desktop/hojas-anexas-form.html',
    './partials/propuesta-flota/desktop/propuesta-flota-agregar.html',
    './partials/propuesta-flota/desktop/propuesta-flota-form.html',
    './partials/propuesta-flota/desktop/riesgo-agregar-form.html',
    './partials/propuesta-flota/desktop/riesgo-form.html',
    './partials/propuesta-flota/desktop/sidebar-flota.html',
    './partials/propuesta-flota/desktop/tomador-form.html',
    './partials/propuesta-hogar/desktop/hogar-form.html',
    './partials/propuesta-multi-riesgos/desktop/propuesta-multiriesgo-form.html',
    './partials/propuesta-multi-riesgos-riesgo/desktop/riesgo-form.html',
    './partials/propuesta-vehiculo/desktop/propuesta-vehiculo-bcp.html',
    './partials/propuesta-vehiculo/desktop/propuesta-vehiculo-form.html',
    './partials/propuesta-vehiculo/desktop/vehiculo-form.html',
    './partials/suplemento/suplemento-anulacion.html',
    './partials/suplemento/suplemento-cambio-auto.html',
    './partials/suplemento/suplemento-documentos.html',
    './partials/suplemento/suplemento-hojas-anexas.html',
    './partials/suplemento/suplemento-list.html',
    './partials/ventanas-emergentes/buscador-cotizacion-partial.html',
    './partials/ventanas-emergentes/buscador-ordenes-compras-partial.html',
    './partials/ventanas-emergentes/buscador-productos-partial.html',
    './partials/ventanas-emergentes/confirmar-partial.html',
    './partials/ventanas-emergentes/dialog-partial.html',
    './partials/ventanas-emergentes/emision-automatica.html',
    './partials/ventanas-emergentes/emision-validacion.html',
    './partials/ventanas-emergentes/informacion-cotizacion.html',
    './partials/ventanas-emergentes/modal-autorizacion-partial.html',
    './partials/ventanas-emergentes/modal-flota.html',
    './partials/ventanas-emergentes/rechazar-partial.html',
    './partials/ventanas-emergentes/show-pdf-partial.html',
    /* END  PARTIALS*/

    
    
    /*  PWA ICONS */
    './img/logo-redondo-1024.png',
    './img/logo-redondo-128.png',
    './img/logo-redondo-192.png',
    './img/logo-redondo-256.png',
    './img/logo-redondo-32.png',
    './img/logo-redondo-384.png',
    './img/logo-redondo-512.png',
    './img/logo-redondo-64.png',
    './img/logo-redondo-96.png',
    './img/logo-redondo-favicon.png',
    /* END PWA ICONS */

    
    /*  PWA FILES */
    './manifest.json',
    './sw.js'
    /* END PWA FILES */
  ]

//durante la fase de instalación, generalmente se almacena en caché los activos estáticos
self.addEventListener('install', e => {
  e.waitUntil(
    caches.open(CACHE_NAME)
      .then(cache => {
        return cache.addAll(urlsToCache)
          .then(() => self.skipWaiting())
      })
      .catch(err => console.log('Falló registro de cache', err))
  )
})

//una vez que se instala el SW, se activa y busca los recursos para hacer que funcione sin conexión
self.addEventListener('activate', e => {
  const cacheWhitelist = [CACHE_NAME]

  e.waitUntil(
    caches.keys()
      .then(cacheNames => {
        return Promise.all(
          cacheNames.map(cacheName => {
            //Eliminamos lo que ya no se necesita en cache
            if (cacheWhitelist.indexOf(cacheName) === -1) {
              return caches.delete(cacheName)
            }
          })
        )
      })
      // Le indica al SW activar el cache actual
      .then(() => self.clients.claim())
  )
})

//cuando el navegador recupera una url
self.addEventListener('fetch', e => {
  //Responder ya sea con el objeto en caché o continuar y buscar la url real
  e.respondWith(
    caches.match(e.request)
      .then(res => {
        if (res) {
          //recuperar del cache
          return res
        }
        //recuperar de la petición a la url
        return fetch(e.request)
      })
  )
})
